#!/bin/bash

# input via stdin
# http://stackoverflow.com/a/18766794/5156190
if [ $# -eq 0 ]; then
    script=$(cat)

# input via cmd
# http://stackoverflow.com/a/12451419/5156190
else
    exec 3>&1
    script=$(stdbuf -e 0 -o 0 bash -c -i "trap echo INT ; $*" |& tee >(cat - >&3))
fi

# URL for POST
if [ -z "$APP_URL" ]; then
    APP_URL=https://help.cs50.net/
fi

# POST /
echo -en "\033[33m";
curl \
    --data-urlencode "cmd=${*}" \
    --data-urlencode "format=txt" \
    --data-urlencode "script=${script}" \
    --data-urlencode "username=${C9_USER}" \
    "$APP_URL"
echo -en "\033[39m"
